### ISSUE TITLE
Bool module not exposed?

### ISSUE THREAD

**Issue by yuhr** [nyuichi/satysfi-base#96]
With satysfi-base v1.2.1 on Satyrographos, we aren't able to `@require: base/bool`, are we?

**Comment by puripuri2100** [comment]
satysfi-base v1.2.1 was released on Mar 27, 2020  (#57 ).
`bool.satyg` was added on Apr 4, 2020  (#74 ).
So `bool.satyg` is not included in satysfi-base v1.2.1.

**Comment by yuhr** [comment]
I see, thanks. By the way what time is the next release planned on? I would appreciate if you could release a new minor version *instantly* when every new feature has been added unless it's not considered conflicting with existing part.
